### ISSUE TITLE
Tag release

### ISSUE THREAD

**Issue by MarioBlazek** [ezcommunity/EzMatrixFieldTypeBundle#11]
Is it possible to tag some release number ? It will make bundle easier to install with composer.

**Comment by crevillo** [comment]
I guess we can tag it as beta somehow... @bdunogier, @andrerom , your pov?

**Comment by andrerom** [comment]
A 0.x version can't harm anyone, feel free :)

**Comment by crevillo** [comment]
Tagged as 0.1.0. let me know if this works for everybody.

**Comment by MarioBlazek** [comment]
Great, thanks.
