### ISSUE TITLE
Enhancement request? Allow ezmatrix fields to contain object references

### ISSUE THREAD

**Issue by nraphael** [ezcommunity/EzMatrixFieldTypeBundle#15]
Forgive me if this facility is already part of the bundle. I have a content situation where I want to correlate a reference to an instance of one class to an instance of another class -- the classes are the means chosen for implementing controlled lists.

Does this ezmatrix update include this facility? What would be involved in providing it through the updated ezmatrix bundle?

Thanks.

**Comment by andrerom** [comment]
The feature is currently not planned for eZ Matrix. Main goal for a stable release here is to have M1: feature parity with legacy version M2: including support for v2 Admin UI so it can be edited on eZ Platform.
