### ISSUE TITLE
Change package name from `ezsystems/` org to `ezcommunity/` in composer.json

### ISSUE THREAD

**Issue by andrerom** [ezcommunity/EzMatrixFieldTypeBundle#27]
To avoid confusion with replacement package: [ezsystems/ezplatform-matrix-fieldtype](https://github.com/ezsystems/ezplatform-matrix-fieldtype/blob/master/composer.json#L2)

I suggest we change name from `ezsystems/ez-matrix-bundle` to `ezcommunity/ez-matrix-bundle` here.

**Comment by andrerom** [comment]
WDYT @crevillo @iherak @joekepley @gggeek @blankse ?

We can also rename repo here to `ez-matrix-bundle` to make it easier to find having same name as composer, github will handle redirects for web and git ssh use.

**Comment by gggeek** [comment]
well 1st change is quite a bc for users who use the bundle already... I am fine with 2nd change if we go w first though.

**Comment by andrerom** [comment]
1st change can be done as a 0.3 release and can be handled by added deprecated on 0.2 with old name and a replaces composer param for the 0.3 new name.
