### ISSUE TITLE
eZ Publish 6.0.0-alpha5

### ISSUE THREAD

**Issue by edgecrusherr** [ezcommunity/EzMatrixFieldTypeBundle#9]
Greetings,

I have been trying unsuccessfully to make this extension work on eZ Publish 6.0.0-alpha5. I am wondering whether there are any plans to bring this extension up to date with the latest eZP version?

Thanks

**Comment by andrerom** [comment]
do you have any more details on what is not working?

**Comment by edgecrusherr** [comment]
Apologies, this was a problem on my side.
